#!/usr/bin/bash
clear
file=$1
#cp $file ~/.java/
#cd ~/.java/
echo "Proses sedang berjalan..."
ecj $file 2> hasil.txt
if [ -s hasil.txt ]; then
	clear
	echo "ERROR FOUND!"
	cat hasil.txt
else
	clear
	dx --dex --output="${file%.*}.dex" "${file%.*}.class"
	dalvikvm -cp "${file%.*}.dex" "${file%.*}" 
fi
rm -rf *.dex *.class oat hasil.txt
